mock_endpoint:
  context_factory: org.apache.activemq.jndi.ActiveMQInitialContextFactory
  provider_url: vm://localhost?broker.persistent=false
  connection_factory_name: ConnectionFactory
  jndi_username: ""
  jndi_password: ""
  jms_username: ""
  jms_password: ""
  request_queue: dynamicQueues/requestQueue
  response_queue: dynamicQueues/responseQueue
  encoding: UTF-8
